openai_api = "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"
activeloop = "eyJhbGciOiJIUzUxMiIsImlhdCI6MTY4Mzk5OTI3NSwiZXhwIjoxNjg0MjU4NDQwfQ.eyJpZCI6InBhc3Npb25tYXgifQ.6BxAn_UR0IoNzRak3SZFcuFWQo9EC4NLVmPtlazxNnh_8FUHlxG9xGZyTsK6e-UfDoHHawiIbHmYGL_frF2GLw"
